project_id = "fgjgofbstljjuiwbnmba"

[functions.send-order-confirmation]
verify_jwt = false

[functions.validate-admin-password]
verify_jwt = false

[functions.get-pet-tag]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false

[functions.activate-on-signup]
verify_jwt = false