project_id = "xzrycwlskxigxgxcyzrj"

[functions.validate-coupon]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.validate-admin-password]
verify_jwt = false

[functions.get-pet-tag]
verify_jwt = false

[functions.validate-activation-code]
verify_jwt = false

[functions.activate-on-signup]
verify_jwt = false

[functions.pix-payment]
verify_jwt = false

[functions.asaas-payment]
verify_jwt = false

[functions.process-credit-card-payment]
verify_jwt = false

[functions.activate-product]
verify_jwt = false

[functions.melhor-envio]
verify_jwt = false
